### ISSUE TITLE
Missing font5x8.bin file

### ISSUE THREAD

**Issue by vitormhenrique** [adafruit/Adafruit_CircuitPython_framebuf#10]
After installing on a raspberry pi and running with adafruit-blinka i get an error:

 <pre><code>Could not find font file font5x8.bin
Traceback (most recent call last):
  File "rfm9x_check.py", line 54, in <module>
    display.text('RFM9x: Detected', 0, 0, 1)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_framebuf.py", line 264, in text
    self._font = BitmapFont()
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_framebuf.py", line 314, in __init__
    self._font = open(self.font_name, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'font5x8.bin'</code></pre>

All libraries are installed correctly, I'm following the tutorial for he Adafruit Lora Radio Bonnet [here](https://learn.adafruit.com/adafruit-radio-bonnets/rfm9x-raspberry-pi-setup)

I could fix the issue by manually coping the font5x8.bin file from an old [repository ](https://github.com/adafruit/micropython-adafruit-bitmap-font) to the location of my python script.

**Comment by brentru** [comment]
The `font5x8.bin` file you're searching for is: https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/master/examples/font5x8.bin

You'll want to copy this file into the location of`rfm9x_check.py`.

I've updated the guide to reflect these steps.

**Comment by ladyada** [comment]
@brentru

**Comment by ladyada** [comment]
@brentru thanks!

**Comment by vitormhenrique** [comment]
@brentru i had it downloaded and working before posting, just wanted to double check.

While you are there you might want to fix the “pip install” instead of the “pip3 install” to get the ssd1306 library.

**Comment by brentru** [comment]
@vitormhenrique  Thanks for the catch, added!

**Comment by moisesdfelix** [comment]
thank you. 
your contribution helped me a lot.

**Comment by josalesmj** [comment]
@brentru thank you, solved my problem. I think this file is missing in original repository
