### ISSUE TITLE
Add font5x8.bin to Bundle

### ISSUE THREAD

**Issue by Tasm-Devil** [adafruit/Adafruit_CircuitPython_framebuf#11]
Hi there!
I'm currently running the `import examples.ssd1306_framebuftest` in Circuitpython4 on a nrf52840 Express board.
I have to copy the **font5x8.bin** manually to the examples folder. Is it possible to add this font in the [Adafruit_CircuitPython_Bundle](https://github.com/adafruit/Adafruit_CircuitPython_Bundle) and locate it by default in the `font` folder in the **CIRCUITPY** device?

**Comment by ladyada** [comment]
i think having it copied into the examples folder would work best?

**Comment by sommersoft** [comment]
On it!

**Comment by sommersoft** [comment]
Got it working locally.
```
(.env) sommersoft@thespacebetween:~/Dev/cpy-build-tools/circuitpython-build-tools/bundles$ unzip -l test-4.x-mpy-1475ae7.zip
Archive:  test-4.x-mpy-1475ae7.zip
{"build-tools-version": "devel"}
  Length      Date    Time    Name
---------  ---------- -----   ----
    1282  2019-02-04 21:49   test-4.x-mpy-1475ae7/examples/font5x8.bin
     997  2019-02-04 21:49   test-4.x-mpy-1475ae7/examples/framebuf_simpletest.py
```
@Tasm-Devil, give it a few days. Gotta push to the `circuitpython-build-tools` repo, then it will get pushed to PyPI, and then the Bundle will build with it included.

**Comment by sommersoft** [comment]
Just to follow up, `font5x8.bin` is now included in the examples folders with the bundle releases.

![capture](https://user-images.githubusercontent.com/21211479/52372373-a4dee500-2a1d-11e9-91df-4cea3b7b41d5.PNG)
