### ISSUE TITLE
Strange characters displaying on OLED (rfm69_check.py)

### ISSUE THREAD

**Issue by rahulkatre-projects** [adafruit/Adafruit_CircuitPython_framebuf#15]
![img_9570](https://user-images.githubusercontent.com/38406805/53684249-15091f80-3cd9-11e9-91e6-371ea537250a.JPG)

I tried running `rfm69_check.py` from the RFM69 Raspberry Pi Setup tutorial (https://learn.adafruit.com/adafruit-radio-bonnets/rfm69-raspberry-pi-setup). The text should be reading: `RFM69: Detected` as shown in the tutorial.

Initially I ran into the issue where the `font5x8.bin` file was missing. To download it to the Pi, I ran 

`curl -o font5x8.bin https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/master/examples/font5x8.bin` 

The `rfm69_check.py` would run properly (the buttons work, as they display some sort of text in the correct position when pressed), but none of the characters are correct. I am running on a Raspberry Pi B+ with the latest version of Raspbian. This is the 915MHz Non-LoRa version of the bonnet. 

Edit: Additionally, my use case for the OLED is just to show the IP address of the Pi when it is connected to any sort of network.

**Comment by brentru** [comment]
The URL for CURL should be:
https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/master/examples/font5x8.bin?raw=true

I just updated the guide to include this url.

**Comment by rahulkatre-projects** [comment]
Ok, I ran the same line but with the URL you gave, and this is what I got: 

`Traceback (most recent call last):`
  
`  File "rfm69_check.py", line 55, in <module>`
    
`    display.text('RFM69: Detected', 0, 0, 1)`

`  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_framebuf.py", line 291, in text
    y, self, color)`
  
`  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_framebuf.py", line 366, in draw_charline = struct.unpack('B', self._font.read(1))[0]`

`struct.error: unpack requires a bytes object of length 1`

**Comment by rahulkatre-projects** [comment]
Update: I got it to work. I reinstalled all the `pip3` libraries and then I ran this line to download `font5x8.bin`:

```
wget -O font5x8.bin https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/master/examplesueont5x8.bin?raw=true
```

**Comment by brentru** [comment]
@rahulkatre-projects Great to hear - I updated the guide to add the `wget` command you had success with. After you installed the libraries, did you try the CURL command you originally tried (`curl -o font5x8.bin https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/master/examples/font5x8.bin?raw=true`)?

**Comment by rahulkatre-projects** [comment]
I'll try removing the file and re-downloading it with CURL. I might have entered the command wrong in the first place (I didn't have `curl -O` at the beginning, just `curl`) so that may have been the cause of my issues. The file did download correctly, which was the confusing part.
