### ISSUE TITLE
framebuf support for ST7565

### ISSUE THREAD

**Issue by roomtek** [adafruit/Adafruit_CircuitPython_framebuf#2]
Hello,

I am trying to write some code for the micropython runnin on an ESP8266 to talk to Adafruit ST7565 GLCD. will this framebuf someday add support for that display, or is the display to "heavy" for the micrpython.

**Comment by ladyada** [comment]
@roomtek hiya this library wont be for micropython anymore, but for circuitpython. that said, you could use it for ST7565 for sure, its 128*64 pixels and SPI, well within possibility :)
