### ISSUE TITLE
Could not find font file font5x8.bin

### ISSUE THREAD

**Issue by ThomasBurgess2000** [adafruit/Adafruit_CircuitPython_framebuf#38]
```
Could not find font file font5x8.bin
Traceback (most recent call last):
  File "sharprefresh.py", line 59, in <module>
    display.text(" hello world!", 0, 0, 0)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_framebuf.py", line 409, in text
    self._font = BitmapFont(font_name)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_framebuf.py", line 484, in __init__
    self._font = open(self.font_name, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'font5x8.bin'
```

**Comment by ladyada** [comment]
look in 
https://github.com/adafruit/Adafruit_CircuitPython_framebuf/tree/master/examples

**Comment by ThomasBurgess2000** [comment]
Ah yeah, that file is not included in this repo: https://github.com/adafruit/Adafruit_CircuitPython_SharpMemoryDisplay/tree/master/examples I'll open an issue there.

**Comment by durapensa** [comment]
When installing a python script that uses Adafruit_CircuitPython_framebuf for system use, font5x8.bin cannot be found. I'm unsure of the path that is set when the script is run, so it seems best to include the dependency font5x8.bin in the Adafruit_CircuitPython_framebuf package for this and other unforeseen cases.

**Comment by durapensa** [comment]
A workaround: I found looking at `dist-packages/adafruit_framebuf.py` that `font_name` can be any FQPN (`self._font = open(self.font_name, "rb")`), so just included that in the function call `text(self, string, x, y, color, *, font_name="font5x8.bin", size=1)` in my script.

**Comment by kittenarmy** [comment]
Fixed it by downloading it this way:

```
(env) pi@raspberrypi:~ $ rm font5x8.bin
(env) pi@raspberrypi:~ $ sudo wget -O font5x8.bin https://github.com/adafruit/Adafruit_CircuitPython_framebuf/blob/main/examples/font5x8.bin?raw=true
```
