### ISSUE TITLE
framebuf support for displayio(ST7789)?

### ISSUE THREAD

**Issue by Meekdai** [adafruit/Adafruit_CircuitPython_framebuf#42]
Is there an example for reference?
I don’t know how to use framebuf as a display memory. I want to use framebuf to change my display content.

**Comment by ladyada** [comment]
you cant use both displayio and framebuf at the same time
here are framebuf-based drivers https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display

**Comment by Meekdai** [comment]
> you cant use both displayio and framebuf at the same time
> here are framebuf-based drivers https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display

Thank you for your reply. I found that using CircuitPython to display and refresh the screen is slower than Micropython at the same MCU. 
Why CircuitPython does not consider this requirement?
