### ISSUE TITLE
Include more fonts.

### ISSUE THREAD

**Issue by JRWR** [adafruit/Adafruit_CircuitPython_framebuf#45]
I propose more fonts for easy of use or to drop in depending on what you need. DisplayIO drivers are rather obtuse and are for large displays for sure, if I need to do something on the level of the u8g project. framebuf seems like a much better fit and easier to learn. The question is. How do I get a few more fonts going so I can have something a little larger on my tiny oled display.

**Comment by ladyada** [comment]
honestly displayio is *way* better than framebuf for font managing, and will work great on oleds - you can choose any font you like!

**Comment by ladyada** [comment]
https://learn.adafruit.com/circuitpython-display-support-using-displayio/text
