### ISSUE TITLE
Create new fonts

### ISSUE THREAD

**Issue by volthouse** [adafruit/Adafruit_CircuitPython_framebuf#9]
Hello,

where can I find other fonts? I tried other font from the Adafruit-GFX-Library for example I copied the array data from FreeMono24pt7b.h to the font_to_bin.py and create a new font binary file, but if I print text to the display, the text is garbage. The example font5x8.bin works well?

**Comment by ladyada** [comment]
hiya the font handling is very hard-coded. for other font support we'll have displayio, which is not complete yet - so basically right now this is the only font you can use :)
